<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyTitle>Steam Achievement Manager</AssemblyTitle>
    <Company>Gibbed</Company>
    <Authors>Gibbed</Authors>
    <Description>A manager for game achievements in Steam.</Description>
    <Copyright>Copyright © Gibbed 2019</Copyright>
  </PropertyGroup>
  <PropertyGroup>
    <Version>7.0.0</Version>
    <AssemblyVersion>7.0.0.0</AssemblyVersion>
    <FileVersion>7.0.0.0</FileVersion>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>Blank.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <PropertyGroup>
    <RepositoryUrl>https://github.com/gibbed/SteamAchievementManager/</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
  </PropertyGroup>
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <LangVersion>12.0</LangVersion>
    <Nullable>disable</Nullable>
    <Platforms>x86</Platforms>
    <PlatformTarget>x86</PlatformTarget>
    <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
    <UseWPF>true</UseWPF>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x86' ">
    <OutputPath>..\bin\</OutputPath>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x86' ">
    <OutputPath>..\upload\</OutputPath>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SAM.API\SAM.API.csproj" />
    <ProjectReference Include="..\SAM.Core\SAM.Core.csproj" />
    <ProjectReference Include="..\SAM.UI\SAM.UI.csproj" />
  </ItemGroup>
</Project>
